return {
  "nvim-treesitter/nvim-treesitter",
  build = function()
    require("nvim-treesitter.install").update({ with_sync = true })()
  end,
  config = function()
    require("nvim-treesitter.configs").setup({
      ensure_installed = {
        "angular",
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "dockerfile",
        "editorconfig",
        "gitignore",
        "gleam",
        "glimmer_javascript",
        "glimmer_typescript",
        "go",
        "goctl",
        "gomod",
        "gosum",
        "java",
        "javadoc",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "luau",
        "make",
        "markdown",
        "markdown_inline",
        "nginx",
        "php",
        "prisma",
        "python",
        "regex",
        "ruby",
        "rust",
        "scss",
        "sql",
        "ssh_config",
        "svelte",
        "tmux",
        "toml",
        "typescript",
        "yaml",
        "yang",
      },
      sync_install = false,
      highlight = {
        enable = true,
        additional_vim_regex_highlighting = false,
      },
      indent = {
        enable = true,
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<leader>h",
          node_incremental = "<leader>h",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    })
  end,
}
